pipeline {
    agent any
    environment {
        PEM_PATH = "C:\\Users\\anmol\\OneDrive\\Documents\\CSE\\donorconnect.pem"
        TEMP_PEM_PATH = "C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\test@tmp\\donorconnect.pem"
        EC2_IP = credentials('EC2_IP')
    }
    stages {
        stage('Prepare PEM File') {
            steps {
                bat """
                copy /Y %PEM_PATH% %TEMP_PEM_PATH%
                icacls %TEMP_PEM_PATH% /inheritance:r /grant:r "NT AUTHORITY\\SYSTEM:(R)"
                icacls %TEMP_PEM_PATH% /remove "BUILTIN\\Users"
                """
            }
        }
        stage('Test SSH Connection') {
            steps {
                bat """
                ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i %TEMP_PEM_PATH% ubuntu@%EC2_IP% "echo SSH works!"
                """
            }
        }
        stage('Build Docker Image on EC2') {
            steps {
                bat '''
                ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i %TEMP_PEM_PATH% ubuntu@%EC2_IP% "mkdir -p /tmp/backend && rm -rf /tmp/backend/*"
                scp -i %TEMP_PEM_PATH% -r ./backend/* ubuntu@%EC2_IP%:/tmp/backend/
                ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i %TEMP_PEM_PATH% ubuntu@%EC2_IP% "cd /tmp/backend && sudo docker build -t backend-local-image ."
                '''
            }
        }
        stage('Deploy Docker Container on EC2') {
            steps {
                bat '''
                ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i %TEMP_PEM_PATH% ubuntu@%EC2_IP% "sudo docker stop donorconnect || true"
                ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i %TEMP_PEM_PATH% ubuntu@%EC2_IP% "sudo docker rm donorconnect || true"
                ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i %TEMP_PEM_PATH% ubuntu@%EC2_IP% "sudo docker run -d --name donorconnect --env-file /home/ubuntu/.env -p 3177:3177 backend-local-image"
                '''
            }
        }
    }
}