pipeline {
    agent any
    environment {
        EC2_IP = credentials('EC2_IP')
        SSH_CREDENTIALS = credentials('EC2_SSH_CREDS')
    }
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image on EC2') {
            steps {
                sshagent(['$SSH_CREDENTIALS']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP << EOF
                    cd /tmp/backend || mkdir -p /tmp/backend
                    rm -rf /tmp/backend/*
                    exit
                    EOF
                    scp -r ./* ec2-user@$EC2_IP:/tmp/backend/
                    ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP << EOF
                    cd /tmp/backend
                    docker build -t backend-local-image .
                    EOF
                    '''
                }
            }
        }
        stage('Deploy Docker Container on EC2') {
            steps {
                sshagent(['$SSH_CREDENTIALS']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP << EOF
                    docker stop donorconnect || true
                    docker rm donorconnect || true
                    docker run -d --name donorconnect -p 3177:3177 backend-local-image
                    EOF
                    '''
                }
            }
        }
    }
}
